platform :ios, '12.0'

project 'AppBDS.xcodeproj'  # <- thêm dòng này

target 'AppBDS' do
  use_frameworks!
  use_modular_headers!

  # Nếu bạn có pods, thêm ở đây, ví dụ:
  # pod 'Alamofire', '~> 5.6'
end
